- name: "Project {{ project.name }} (id:{{ project.id }}) is tagged as quota propagation disabled ({{ disabled_project_tag }})"
  when: disabled_project_tag in project.tags
  ansible.builtin.debug:
    msg: "Project {{ project.id }} disables quota propagation with tag: {{ disabled_project_tag }}."

- name: "Project {{ project.name }} quota propagation enabled"
  when: disabled_project_tag not in project.tags
  block:

  - name: "Propagate PARENT_PROJECT {{ PARENT_PROJECT.projects[0].name }} (id:{{ PARENT_PROJECT.projects[0].id }}) quota to child project {{ project.name }} (id:{{ project.id }})"
    openstack.cloud.quota:
      name: "{{ project.id }}"
      cores: "{{ PARENT_PROJECT_QUOTA.quotas.compute.cores }}"
      instances: "{{ PARENT_PROJECT_QUOTA.quotas.compute.instances }}"
      key_pairs: "{{ PARENT_PROJECT_QUOTA.quotas.compute.key_pairs }}"
      ram: "{{ PARENT_PROJECT_QUOTA.quotas.compute.ram }}"
      server_group_members: "{{ PARENT_PROJECT_QUOTA.quotas.compute.server_group_members }}"
      server_groups: "{{ PARENT_PROJECT_QUOTA.quotas.compute.server_groups }}"
      floating_ips: "{{ PARENT_PROJECT_QUOTA.quotas.network.floating_ips }}"
      network: "{{ PARENT_PROJECT_QUOTA.quotas.network.networks }}"
      port: "{{ PARENT_PROJECT_QUOTA.quotas.network.ports }}"
      rbac_policy: "{{ PARENT_PROJECT_QUOTA.quotas.network.rbac_policies }}"
      router: "{{ PARENT_PROJECT_QUOTA.quotas.network.routers }}"
      security_group: "{{ PARENT_PROJECT_QUOTA.quotas.network.security_groups }}"
      security_group_rule: "{{ PARENT_PROJECT_QUOTA.quotas.network.security_group_rules }}"
      subnet: "{{ PARENT_PROJECT_QUOTA.quotas.network.subnets }}"
      subnetpool: "{{ PARENT_PROJECT_QUOTA.quotas.network.subnet_pools }}"
      backup_gigabytes: "{{ PARENT_PROJECT_QUOTA.quotas.volume.backup_gigabytes }}"
      backups: "{{ PARENT_PROJECT_QUOTA.quotas.volume.backups }}"
      gigabytes: "{{ PARENT_PROJECT_QUOTA.quotas.volume.gigabytes }}"
      per_volume_gigabytes: "{{ PARENT_PROJECT_QUOTA.quotas.volume.per_volume_gigabytes }}"
      snapshots: "{{ PARENT_PROJECT_QUOTA.quotas.volume.snapshots }}"
      volumes: "{{ PARENT_PROJECT_QUOTA.quotas.volume.volumes }}"
